### ISSUE TITLE
Add GitHub hook to automatically rebuild website

### ISSUE THREAD

**Issue by clepple** [networkupstools/nut-website#4]
This requires specifying a codebase to Buildbot, and filtering the commits in both schedulers.

Also, it may be preferable to have a separate builder to handle man pages and documentation outside of the website update cycle (or we should add a step to automatically update the nut submodule).

**Comment by jimklimov** [comment]
Note: since recently, we have Travis CI integration https://travis-ci.org/networkupstools/nut-website that can build the site upon commits, or at least goes a long way towards that.

Travis technology has a way to securely store credentials for e.g. publishing of release tarballs upon green commits merged into master branches, etc. - probably that can be used to push the website as well.

**Comment by jimklimov** [comment]
Further work done last and this year got the site rebuild automation to the point that NUT CI farm can build it regularly now and push to public site repo. This happens for git-push webhook for nut-website project, and as a timed job (every 3 hours at the moment) to gobble up master-branch changes of component repositories (currently: nut, ddl, source, archive).
