### ISSUE TITLE
/protocols/snmp/ content is missing

### ISSUE THREAD

**Issue by clepple** [networkupstools/nut-website#8]
It appears that we have not included /protocols/snmp in this git repository. This mostly seems to be copies of MIB files.

**Comment by clepple** [comment]
@aquette do you have a backup of this?

**Comment by zykh** [comment]
@clepple: https://github.com/networkupstools/nut-website/tree/master/protocols/static/snmp
Apparently, I forgot to update the links in ups-protocols.txt.

**Comment by zykh** [comment]
aehm.. I better get a check-up for Alzheimer's.. protocols/static/snmp/ + make -> output/protocols/snmp/

**Comment by aquette** [comment]
Hi @clepple and @zykh , have I missed something or can the bug be closed? as pointed by @zykh , the files are in protocols/static/snmp, and I even added some files recently...

**Comment by clepple** [comment]
@aquette I didn't have a chance to check the links until just now. http://networkupstools.org/ups-protocols.html <http://networkupstools.org/ups-protocols.html> works much better.

@zykh anything else?

**Comment by zykh** [comment]
I grepped 'protocols/snmp' and, in nut repo, I get:
```
./drivers/delta_ups-mib.c: *  MIB reference: http://www.networkupstools.org/ups-protocols/snmp/DeltaUPSv4.mib
./docs/man/snmp-ups.txt:Available at: http://www.networkupstools.org/protocols/snmp/
./docs/snmp.txt:http://random.networkupstools.org/protocols/snmp/
```
- Does anyone have that 'DeltaUPSv4.mib' file?
  Any chance it was the same file (UPSv4.mib) attached (compressed) [here](http://lists.alioth.debian.org/pipermail/nut-upsuser/2012-October/008024.html)?
- We need to either generate an index (à la source/ and package/ subdirs) for the snmp directory or change those urls (the 'random' and the 'delta_ups' ones have to be updated anyway).

**Comment by aquette** [comment]
* the Delta UPS MIB is indeed the one you pointed @zykh ; I've just added it to the repos, along with a reference in the protocols page. I've ensured that the name is the same as the one referenced in the driver too ( 06a8cac ).
* I've also updated the references to the SNMP section of the protocols page (https://github.com/networkupstools/nut/commit/ea589cde1c9c021e42b344f37463dc6dbb73ece9)
* I'm not sure we need the index listing here, since there needs to be some descriptive references to the files, and not just a listing.
* finally, we should get rid of the "ups" part, and just rename to "protocols" everywhere... I've created another ticket for that one ( #9 )
